name: requirements-project
  # Este pipeline ejecuta las validaciones de seguridad de sonar y lint y security checks (validación de credenciales).
  # IMPORTANTE: Éste pipeline se ejecuta SOLO MANUALMENTE.

on:
  workflow_dispatch:

jobs:
  requirements:
    uses: xxxxx/xxxx-xxxx-xx-xxx-xxx/.xxx/xxx/xxxx_xxxxx.yml@v7
    with:
      project-name: bbog-xxxx-xxxxxx-automated-testing
      project-key: bbog-xxxx-xxxxxx-automated-testing
      language: java
      sonar-project-properties-file: 'sonar-project-custom.properties'
    secrets: inherit