name: requirements-project
# Este pipeline ejecuta las validaciones de seguridad de sonar y lint y security checks (validación de credenciales).
# IMPORTANTE: Éste pipeline se ejecuta automáticamente.

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL objetivo para el escaneo de seguridad 002'
        required: true
        default: 'https://opensource-demo.orangehrmlive.com'
      zap_options:
        description: 'Opciones adicionales para ZAP'
        required: false
        default: '-t 60 -a'

jobs:
  requirements:
    # cambiar la siguiente línea después de uses: por lo siguiente: bancodebogota/bbog-dig-do-testing-pipeline/.github/workflows/requirements_frontend.yml@v7
    uses: xxxxx/xxxx-xxxx-xx-xxx-xxx/.xxx/xxx/xxxx_xxxxx.yml@v7
    with:
      # coloque el nombre de su proyecto de Github
      project-name: bbog-xxxx-xxxxxx-automated-testing
      # repita nuevamente el nombre de su proyecto de Github
      project-key: bbog-xxxx-xxxxxx-automated-testing
      language: java
      # este archivo esta en la raiz del proyecto
      sonar-project-properties-file: 'sonar-project-custom.properties'
    secrets: inherit