name: security-testing

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL objetivo para el escaneo de seguridad'
        required: true
        default: 'https://opensource-demo.orangehrmlive.com'
      zap_options:
        description: 'Opciones adicionales para ZAP'
        required: false
        default: '-t 60 -a'

jobs:
  jobs:
    zap_scan:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Run ZAP Baseline Scan
          run: |
            docker run --user root --rm \
              -v ${{ github.workspace }}:/zap/wrk/:rw \ghcr.io/zaproxy/zaproxy:stable \zap-baseline.py -t https://opensource-demo.orangehrmlive.com -r zap_report.html

        - name: Upload ZAP Report
          uses: actions/upload-artifact@v3
          with:
            name: zap-report
            path: zap_report.html

        - name: Upload ZAP Reports
          uses: actions/upload-artifact@v4
          with:
            name: zap-security-reports
            path: |
              zap_report.html
              zap_report.md
            if-no-files-found: warn

        - name: Check for critical findings
          run: |
            if grep -q "High" zap_report.html; then
              echo "::error::Se encontraron vulnerabilidades de alta prioridad"
              exit 1
            fi