name: security-testing

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL objetivo para el escaneo de seguridad'
        required: true
        default: 'https://opensource-demo.orangehrmlive.com'
      zap_options:
        description: 'Opciones adicionales para ZAP'
        required: false
        default: '-t 60 -a'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: OWASP ZAP Security Scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run OWASP ZAP Baseline Scan using GHCR
        run: |
          docker run -v $(pwd):/zap/wrk \--user root \ghcr.io/zaproxy/zaproxy:stable \zap.sh -cmd -autorun /zap/wrk/zap.yaml
            -t https://opensource-demo.orangehrmlive.com/web/index.php/auth/login \
            -r zap_report.html \
            -x zap_report.xml \
            -J zap_report.json

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-security-reports
          path: |
            zap_report.html
            zap_report.md
          if-no-files-found: warn

      - name: Check for critical findings
        run: |
          if grep -q "High" zap_report.html; then
            echo "::error::Se encontraron vulnerabilidades de alta prioridad"
            exit 1
          fi