name: security-testing

on:
  workflow_dispatch:
    inputs:
      release_id:
        type: string
        description: Prueba pipeline de Seguridad demo
        required: true
jobs:
  integration-security-tests:
    uses: https://github.com/LuisLopez84/Template_full_Serenity_Screenplay_Chrome/actions/workflows/security-testing.yml@v7
    with:
      repository: 'Template_full_Serenity_Screenplay_Chrome'
      target-url-zap: 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'
      release_id_steward: '001'
      prefix_team: 'LLO'