name: Serenity BDD Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Serenity tests with maximum verbosity
        run: |
          mvn clean verify \
            -Dserenity.console.headings=normal \
            -Dserenity.console.colors=true \
            -Dserenity.logging=VERBOSE \
            -Dserenity.reports.show.step.details=true \
            -Dserenity.take.screenshots=FOR_EACH_ACTION \
            -Dserenity.console.width=132 \
            -Dcucumber.plugin="pretty,html:target/cucumber-reports/cucumber.html" \
            -Dserenity.outputDirectory=target/site/serenity \
            -Dmaven.test.failure.ignore=true \
            -B -e -X
        env:
          JAVA_OPTS: "-Xmx2048m -XX:+TieredCompilation -XX:TieredStopAtLevel=1"

      - name: Archive Serenity Report
        if: success() || failure()
        uses: actions/upload-artifact@v4
#        if: always()
        with:
          name: serenity-report
          path: target/site/serenity
          if-no-files-found: warn